### ISSUE TITLE
bake fails on newer pysqlite

### ISSUE THREAD

**Issue by mikaelj** [oe-lite/core#96]
pysqlite-2.8.1 / sqlite-3.10.2

    ERROR: exception in bake.run()
    
    Traceback (most recent call last):
     File "/usr/lib/python2.7/site-packages/oe_lite-4.2.0.post0-py2.7.egg/oebakery/cmd/cmds.py", line 137, in call
       ret = function(*args)
     File "/home/rijo/repos/tlabos/meta/core/lib/oelite/cmd/bake.py", line 35, in run
       return baker.bake()
     File "/home/rijo/repos/tlabos/meta/core/lib/oelite/baker.py", line 289, in bake
       self.options.rebuild, self.options.relax)
     File "/home/rijo/repos/tlabos/meta/core/lib/oelite/runq.py", line 26, in __init__
       self.cookbook.db.execute("ATTACH ':memory:' AS runq")
    OperationalError: cannot ATTACH database within transaction
    
    CRITICAL: bake failed: Exception: cannot ATTACH database within transaction

Solved by adding `self.cookbook.db.execute("END TRANSACTION")` at core/lib/oelite/runq.py:26

**Comment by kimrhh** [comment]
auch, thanks for reporting
